apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Logs
    type: prometheus
    access: proxy
    url: http://loki:3100/loki

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
